from . import base
from . import conv
from . import conv_last
from . import fc
from . import fc_last
from . import relu
from . import maxpool
from . import avgpool
from . import flatten
from . import shortcut
from . import softmax
from . import identity
from . import identity_local
