from . import base
from . import conv
from . import fc
from . import relu
from . import maxpool
from . import avgpool
from . import flatten
from . import shortcut
from . import last_conv
from . import last_fc
from . import softmax
